base_url = "https://writethagoras.vercel.app"
title = "Writethagoras"
description = "A Place Further than the Universe"
theme = "archie-zola"
default_language = "en"
taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "one-light"
style = "inline"

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/jirbthagoras"

[[extra.social]]
icon = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/jabriel-hans-talula"

[extra.translations]
languages = [{ name = "en", url = "/" }]

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 1 },
    { name = "Posts", url = "/posts", weight = 2 },
    { name = "Tags", url = "/tags", weight = 3 },
]
